### ISSUE TITLE
Web-Ui Issues

### ISSUE THREAD

**Issue by justmesr** [Lumeer/engine#111]

**Comment by justmesr** [comment]
When openning icon-color picker on new, uninitialized collection.
![image](https://user-images.githubusercontent.com/15381356/34339861-795dafb8-e97a-11e7-9408-5327f843a45c.png)

**Comment by justmesr** [comment]
Creating new uninitialized collections takes more and more time as more are added
![image](https://user-images.githubusercontent.com/15381356/34340514-7d383922-e985-11e7-9205-b95f30db17de.png)

**Comment by justmesr** [comment]
Color - icon picker sometimes pops up when navigating to documents of collection

**Comment by justmesr** [comment]
Unused deprecated method `getAttributes` can be removed from `collection.service.ts`

**Comment by justmesr** [comment]
Unused file `mock-data.ts` can be removed.

**Comment by justmesr** [comment]
When organization and project are selected, cllicking on an organization hides `Use Project` button, without deselecting project.

**Comment by livthomas** [comment]
Why has this issue been created in the engine repository?

**Comment by marvec** [comment]
I would suggest to resolve this on our meeting. I think it does not make sense to have it on GitHub at all.

**Comment by justmesr** [comment]
@livthomas Because I can't create any issues in `web-ui` repository. And wanted to track the issues I found somewhere.

**Comment by justmesr** [comment]
After navigating in search to documents:
![image](https://user-images.githubusercontent.com/15381356/34362473-2fc582c2-ea74-11e7-81ef-2a7420b33517.png)

**Comment by justmesr** [comment]
Recently used doesn't wrap names:
![image](https://user-images.githubusercontent.com/15381356/34383607-a22af76e-eb16-11e7-90e0-3f50004a0e36.png)

**Comment by justmesr** [comment]
![image](https://user-images.githubusercontent.com/15381356/34389567-9df82684-eb3a-11e7-89db-ee3d2ac9ab45.png)

**Comment by justmesr** [comment]
Query not clearing on navigation:
![image](https://user-images.githubusercontent.com/15381356/34389924-c84520de-eb3c-11e7-845a-a99f1c88df9f.png)

**Comment by justmesr** [comment]
Navigating homepage (page with favourites) to workspace chooser:
![image](https://user-images.githubusercontent.com/15381356/34436191-920f04b4-ec93-11e7-8904-6fd8a27141e8.png)

**Comment by justmesr** [comment]
No icon or color on new created and updated collection in search bar:
![image](https://user-images.githubusercontent.com/15381356/34439019-4fb8f814-ecab-11e7-94d0-7dc75e61e151.png)

**Comment by justmesr** [comment]
Bad loading icon after recent changes:
![peek 2017-12-29 15-18](https://user-images.githubusercontent.com/15381356/34439055-98c08432-ecab-11e7-9bab-f83e9bad864d.gif)

**Comment by justmesr** [comment]
Store returning a function alongside collections:
![peek 2017-12-30 00-52](https://user-images.githubusercontent.com/15381356/34449716-c518d7a0-ecfb-11e7-93a2-a71ac7e2324c.gif)
